version: '3.8'
services:
  # app:
  #   build: .
  #   ports:
  #     - "4000:4000"
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - app.env

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=time_manager_backend_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5500:5432"