export { default as Sidebar } from '@/components/Sidebar.vue'
export { default as WorkingTimes } from '@/components/WorkingTimes.vue'
export { default as WorkingTime } from '@/components/WorkingTime.vue'
export { default as ClockManager } from '@/components/ClockManager.vue'
export { default as Loader } from '@/components/Loader.vue'
