name: publish

on:
  push:
    branches: ['setup/deployment']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ogesebastien1/timemanager:latest 
  GH_SECRET: ${{ secrets.GH_SECRET }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_PORT: ${{ secrets.SSH_PORT }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_USER: ${{ secrets.SSH_USER }}
  WORK_DIR: ${{ secrets.WORK_DIR }}

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: login
        run: |
          echo ${{ secrets.GH_SECRET }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and Publish
        run: |

          ls -l ./Client
        
          ls -l ./Client/Dockerfile
        
          docker build ./Client --tag ghcr.io/ogesebastien1/timemanager-client:latest
          docker push ghcr.io/ogesebastien1/timemanager-client:latest

  deploy:
    needs: publish
    name: deploy image
    runs-on: ubuntu-latest

    steps:
      - name: install ssh keys
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          touch $HOME/.ssh/config

      - name: configure SSH client
        run: |
          cat <<END > $HOME/.ssh/config
            Host vps
                HostName ${{ secrets.SSH_HOST }}
                User ${{ secrets.SSH_USER }}
                Port ${{ secrets.SSH_PORT }}
                IdentityFile $HOME/.ssh/id_rsa
                StrictHostKeyChecking no
            END

      - name: add SSH host key to known_hosts
        run: |
          touch $HOME/.ssh/known_hosts
          ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> $HOME/.ssh/known_hosts

      - name: connect and pull
        run: ssh vps "cd ${{ secrets.WORK_DIR }} && docker compose pull && docker compose up -d"
        
      - name: cleanup
        run: rm -rf ~/.ssh