name: Deploy to VPS

on:
  push:
    branches:
      - setup/deployment 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to VPS
      run: |
         scp -o StrictHostKeyChecking=no -P ${{ secrets.SSH_PORT }} -r ./ ${{ secrets.SSH_USER}}@${{ secrets.SSH_HOST }}:/timeManager

    - name: SSH and deploy
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /timeManager

          docker-compose up --build -d
        EOF
