name: publish and deploy

on:
  push:
    branches:
      - setup/deployment

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: login
        run: |
          echo ${{ secrets.GHCR_PASSWORD }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
      - name: Build and Publish
        run: |
          docker build ./Client --tag ghcr.io/ogesebastien1/timemanager-client:latest
          docker push ghcr.io/ogesebastien1/timemanager-client:latest

  deploy:
    needs: publish
    name: deploy image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker system prune -f
            docker rm -f $(docker ps -a -q)
            cd ${{ secrets.WORK_DIR }}
            echo ${{ secrets.GHCR_PASSWORD }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
            docker-compose down
            docker-compose pull
            docker-compose up -d
      - name: cleanup
        run: rm -rf ~/.ssh