name: publish

on:
  push:
    branches: ['setup/deployment']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ogesebastien1/timemanager:latest 


jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: login
        run: |
          echo ${{ secrets.GH_SECRET }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and Publish
        run: |
          docker build ./Client --tag ghcr.io/ogesebastien1/timemanager-client:latest
          docker push ghcr.io/ogesebastien1/timemanager-client:latest
        
  deploy:
    needs: publish
    name: deploy image
    runs-on: ubuntu-latest

    steps:
      - name: connect and pull
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.SSH_PORT }}
            script: |
                 docker system prune 
                 docker rm $(docker ps -a -q)
                 cd ${{ secrets.WORK_DIR }}
                 echo ${{ secrets.GH_SECRET }} | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
                 docker pull ghcr.io/ogesebastien1/timemanager-client:latest
                 docker compose up -d

      - name: cleanup
        run: rm -rf ~/.ssh